# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Mainwindow_Inventory.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(720, 500)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(720, 500))
        MainWindow.setMaximumSize(QtCore.QSize(720, 500))
        MainWindow.setStyleSheet("background-color: rgb(255, 97, 66);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Beeftable = QtWidgets.QTableWidget(self.centralwidget)
        self.Beeftable.setGeometry(QtCore.QRect(30, 60, 311, 192))
        self.Beeftable.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Beeftable.setObjectName("Beeftable")
        self.Beeftable.setColumnCount(3)
        self.Beeftable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.Beeftable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Beeftable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Beeftable.setHorizontalHeaderItem(2, item)
        self.Porktable = QtWidgets.QTableWidget(self.centralwidget)
        self.Porktable.setGeometry(QtCore.QRect(380, 60, 311, 192))
        self.Porktable.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Porktable.setObjectName("Porktable")
        self.Porktable.setColumnCount(3)
        self.Porktable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.Porktable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Porktable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Porktable.setHorizontalHeaderItem(2, item)
        self.Chickentable = QtWidgets.QTableWidget(self.centralwidget)
        self.Chickentable.setGeometry(QtCore.QRect(30, 280, 311, 192))
        self.Chickentable.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Chickentable.setObjectName("Chickentable")
        self.Chickentable.setColumnCount(3)
        self.Chickentable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.Chickentable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Chickentable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Chickentable.setHorizontalHeaderItem(2, item)
        self.Beeflabel = QtWidgets.QLabel(self.centralwidget)
        self.Beeflabel.setGeometry(QtCore.QRect(170, 40, 31, 16))
        font = QtGui.QFont()
        font.setFamily("Modern No. 20")
        font.setPointSize(11)
        self.Beeflabel.setFont(font)
        self.Beeflabel.setObjectName("Beeflabel")
        self.Porklabel = QtWidgets.QLabel(self.centralwidget)
        self.Porklabel.setGeometry(QtCore.QRect(510, 40, 47, 13))
        font = QtGui.QFont()
        font.setFamily("Modern No. 20")
        font.setPointSize(11)
        self.Porklabel.setFont(font)
        self.Porklabel.setObjectName("Porklabel")
        self.Chickenlabel = QtWidgets.QLabel(self.centralwidget)
        self.Chickenlabel.setGeometry(QtCore.QRect(150, 260, 61, 16))
        font = QtGui.QFont()
        font.setFamily("Modern No. 20")
        font.setPointSize(11)
        self.Chickenlabel.setFont(font)
        self.Chickenlabel.setObjectName("Chickenlabel")
        self.Refreshbutton = QtWidgets.QPushButton(self.centralwidget)
        self.Refreshbutton.setGeometry(QtCore.QRect(370, 320, 91, 31))
        self.Refreshbutton.setStyleSheet("background-color: rgb(255, 193, 46);")
        self.Refreshbutton.setObjectName("Refreshbutton")
        self.Updatebutton = QtWidgets.QPushButton(self.centralwidget)
        self.Updatebutton.setGeometry(QtCore.QRect(370, 280, 91, 31))
        self.Updatebutton.setStyleSheet("background-color: rgb(255, 193, 46);")
        self.Updatebutton.setObjectName("Updatebutton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(260, 10, 201, 21))
        font = QtGui.QFont()
        font.setFamily("Modern No. 20")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.Orderbutton = QtWidgets.QPushButton(self.centralwidget)
        self.Orderbutton.setGeometry(QtCore.QRect(370, 360, 91, 31))
        self.Orderbutton.setStyleSheet("background-color: rgb(255, 193, 46);")
        self.Orderbutton.setObjectName("Orderbutton")
        self.Logoutbutton = QtWidgets.QPushButton(self.centralwidget)
        self.Logoutbutton.setGeometry(QtCore.QRect(620, 440, 91, 31))
        self.Logoutbutton.setStyleSheet("background-color: rgb(255, 193, 46);")
        self.Logoutbutton.setObjectName("Logoutbutton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        item = self.Beeftable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Product"))
        item = self.Beeftable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Unit price"))
        item = self.Beeftable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Stock"))
        item = self.Porktable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Product"))
        item = self.Porktable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Unit price"))
        item = self.Porktable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Stock"))
        item = self.Chickentable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Product"))
        item = self.Chickentable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Unit price"))
        item = self.Chickentable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Stock"))
        self.Beeflabel.setText(_translate("MainWindow", "Beef"))
        self.Porklabel.setText(_translate("MainWindow", "Pork"))
        self.Chickenlabel.setText(_translate("MainWindow", "Chicken"))
        self.Refreshbutton.setText(_translate("MainWindow", "Refresh"))
        self.Updatebutton.setText(_translate("MainWindow", "Update"))
        self.label.setText(_translate("MainWindow", "Meat Products Inventory"))
        self.Orderbutton.setText(_translate("MainWindow", "Place order"))
        self.Logoutbutton.setText(_translate("MainWindow", "Log out"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

