from PyQt5 import QtCore, QtGui, QtWidgets
import Main_Program_Design_Edit_Prices_New

class Ui_MainWindow(object):
    def openWindow(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Main_Program_Design_Edit_Prices_New.Ui_MainWindow()
        self.ui.setupUi(self.window)
        self.window.show()
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(721, 407)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        MainWindow.setMouseTracking(False)
        MainWindow.setTabletTracking(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setGeometry(QtCore.QRect(0, 0, 721, 421))
        self.frame_4.setAutoFillBackground(False)
        self.frame_4.setStyleSheet("background-color: rgb(255, 179, 85);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.Chicken_Frame = QtWidgets.QFrame(self.frame_4)
        self.Chicken_Frame.setGeometry(QtCore.QRect(490, 50, 221, 259))
        self.Chicken_Frame.setToolTipDuration(-5)
        self.Chicken_Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Chicken_Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Chicken_Frame.setObjectName("Chicken_Frame")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.Chicken_Frame)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.horizontalLayout_55 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_55.setObjectName("horizontalLayout_55")
        self.Chicken_Feet = QtWidgets.QLabel(self.Chicken_Frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Chicken_Feet.setFont(font)
        self.Chicken_Feet.setObjectName("Chicken_Feet")
        self.horizontalLayout_55.addWidget(self.Chicken_Feet)
        self.Chicken_Feet_Price = QtWidgets.QLineEdit(self.Chicken_Frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Chicken_Feet_Price.setFont(font)
        self.Chicken_Feet_Price.setAutoFillBackground(False)
        self.Chicken_Feet_Price.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Chicken_Feet_Price.setText("")
        self.Chicken_Feet_Price.setReadOnly(True)
        self.Chicken_Feet_Price.setObjectName("Chicken_Feet_Price")
        self.horizontalLayout_55.addWidget(self.Chicken_Feet_Price)
        self.Chicken_Feet_Quantity = QtWidgets.QSpinBox(self.Chicken_Frame)
        self.Chicken_Feet_Quantity.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Chicken_Feet_Quantity.setObjectName("Chicken_Feet_Quantity")
        self.horizontalLayout_55.addWidget(self.Chicken_Feet_Quantity)
        self.gridLayout_7.addLayout(self.horizontalLayout_55, 9, 0, 1, 1)
        self.horizontalLayout_60 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_60.setObjectName("horizontalLayout_60")
        self.Chicken_Drumstick = QtWidgets.QLabel(self.Chicken_Frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Chicken_Drumstick.setFont(font)
        self.Chicken_Drumstick.setObjectName("Chicken_Drumstick")
        self.horizontalLayout_60.addWidget(self.Chicken_Drumstick)
        self.Chicken_Drumstick_Price = QtWidgets.QLineEdit(self.Chicken_Frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Chicken_Drumstick_Price.setFont(font)
        self.Chicken_Drumstick_Price.setAutoFillBackground(False)
        self.Chicken_Drumstick_Price.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Chicken_Drumstick_Price.setText("")
        self.Chicken_Drumstick_Price.setReadOnly(True)
        self.Chicken_Drumstick_Price.setObjectName("Chicken_Drumstick_Price")
        self.horizontalLayout_60.addWidget(self.Chicken_Drumstick_Price)
        self.Chicken_Drumstick_Quantity = QtWidgets.QSpinBox(self.Chicken_Frame)
        self.Chicken_Drumstick_Quantity.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Chicken_Drumstick_Quantity.setObjectName("Chicken_Drumstick_Quantity")
        self.horizontalLayout_60.addWidget(self.Chicken_Drumstick_Quantity)
        self.gridLayout_7.addLayout(self.horizontalLayout_60, 6, 0, 1, 1)
        self.horizontalLayout_53 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_53.setObjectName("horizontalLayout_53")
        self.Chicken_Liver = QtWidgets.QLabel(self.Chicken_Frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Chicken_Liver.setFont(font)
        self.Chicken_Liver.setObjectName("Chicken_Liver")
        self.horizontalLayout_53.addWidget(self.Chicken_Liver)
        self.Chicken_Liver_Price = QtWidgets.QLineEdit(self.Chicken_Frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Chicken_Liver_Price.setFont(font)
        self.Chicken_Liver_Price.setAutoFillBackground(False)
        self.Chicken_Liver_Price.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Chicken_Liver_Price.setText("")
        self.Chicken_Liver_Price.setReadOnly(True)
        self.Chicken_Liver_Price.setObjectName("Chicken_Liver_Price")
        self.horizontalLayout_53.addWidget(self.Chicken_Liver_Price)
        self.Chicken_Liver_Quantity = QtWidgets.QSpinBox(self.Chicken_Frame)
        self.Chicken_Liver_Quantity.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Chicken_Liver_Quantity.setObjectName("Chicken_Liver_Quantity")
        self.horizontalLayout_53.addWidget(self.Chicken_Liver_Quantity)
        self.gridLayout_7.addLayout(self.horizontalLayout_53, 8, 0, 1, 1)
        self.horizontalLayout_58 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_58.setObjectName("horizontalLayout_58")
        self.Chicken_Gizzard = QtWidgets.QLabel(self.Chicken_Frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Chicken_Gizzard.setFont(font)
        self.Chicken_Gizzard.setObjectName("Chicken_Gizzard")
        self.horizontalLayout_58.addWidget(self.Chicken_Gizzard)
        self.Chicken_Gizzard_Price = QtWidgets.QLineEdit(self.Chicken_Frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Chicken_Gizzard_Price.setFont(font)
        self.Chicken_Gizzard_Price.setAutoFillBackground(False)
        self.Chicken_Gizzard_Price.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Chicken_Gizzard_Price.setText("")
        self.Chicken_Gizzard_Price.setReadOnly(True)
        self.Chicken_Gizzard_Price.setObjectName("Chicken_Gizzard_Price")
        self.horizontalLayout_58.addWidget(self.Chicken_Gizzard_Price)
        self.Chicken_Gizzard_Quantity = QtWidgets.QSpinBox(self.Chicken_Frame)
        self.Chicken_Gizzard_Quantity.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Chicken_Gizzard_Quantity.setObjectName("Chicken_Gizzard_Quantity")
        self.horizontalLayout_58.addWidget(self.Chicken_Gizzard_Quantity)
        self.gridLayout_7.addLayout(self.horizontalLayout_58, 7, 0, 1, 1)
        self.horizontalLayout_57 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_57.setObjectName("horizontalLayout_57")
        self.Chicken_Breast = QtWidgets.QLabel(self.Chicken_Frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Chicken_Breast.setFont(font)
        self.Chicken_Breast.setObjectName("Chicken_Breast")
        self.horizontalLayout_57.addWidget(self.Chicken_Breast)
        self.Chicken_Breast_Price = QtWidgets.QLineEdit(self.Chicken_Frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Chicken_Breast_Price.setFont(font)
        self.Chicken_Breast_Price.setAutoFillBackground(False)
        self.Chicken_Breast_Price.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Chicken_Breast_Price.setText("")
        self.Chicken_Breast_Price.setReadOnly(True)
        self.Chicken_Breast_Price.setObjectName("Chicken_Breast_Price")
        self.horizontalLayout_57.addWidget(self.Chicken_Breast_Price)
        self.Chicken_Breast_Quantity = QtWidgets.QSpinBox(self.Chicken_Frame)
        self.Chicken_Breast_Quantity.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Chicken_Breast_Quantity.setObjectName("Chicken_Breast_Quantity")
        self.horizontalLayout_57.addWidget(self.Chicken_Breast_Quantity)
        self.gridLayout_7.addLayout(self.horizontalLayout_57, 3, 0, 1, 1)
        self.horizontalLayout_56 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_56.setObjectName("horizontalLayout_56")
        self.Chicken = QtWidgets.QLabel(self.Chicken_Frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Chicken.setFont(font)
        self.Chicken.setObjectName("Chicken")
        self.horizontalLayout_56.addWidget(self.Chicken)
        self.line_10 = QtWidgets.QFrame(self.Chicken_Frame)
        self.line_10.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.horizontalLayout_56.addWidget(self.line_10)
        self.Chicken_Prices = QtWidgets.QLabel(self.Chicken_Frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Chicken_Prices.setFont(font)
        self.Chicken_Prices.setStyleSheet("")
        self.Chicken_Prices.setObjectName("Chicken_Prices")
        self.horizontalLayout_56.addWidget(self.Chicken_Prices)
        self.line_11 = QtWidgets.QFrame(self.Chicken_Frame)
        self.line_11.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.horizontalLayout_56.addWidget(self.line_11)
        self.Chicken_Quantities = QtWidgets.QLabel(self.Chicken_Frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Chicken_Quantities.setFont(font)
        self.Chicken_Quantities.setStyleSheet("")
        self.Chicken_Quantities.setObjectName("Chicken_Quantities")
        self.horizontalLayout_56.addWidget(self.Chicken_Quantities)
        self.gridLayout_7.addLayout(self.horizontalLayout_56, 0, 0, 1, 1)
        self.horizontalLayout_61 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_61.setObjectName("horizontalLayout_61")
        self.Chicken_Whole = QtWidgets.QLabel(self.Chicken_Frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Chicken_Whole.setFont(font)
        self.Chicken_Whole.setObjectName("Chicken_Whole")
        self.horizontalLayout_61.addWidget(self.Chicken_Whole)
        self.Chicken_Whole_Price = QtWidgets.QLineEdit(self.Chicken_Frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Chicken_Whole_Price.setFont(font)
        self.Chicken_Whole_Price.setAutoFillBackground(False)
        self.Chicken_Whole_Price.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Chicken_Whole_Price.setText("")
        self.Chicken_Whole_Price.setReadOnly(True)
        self.Chicken_Whole_Price.setObjectName("Chicken_Whole_Price")
        self.horizontalLayout_61.addWidget(self.Chicken_Whole_Price)
        self.Chicken_Whole_Quantity = QtWidgets.QSpinBox(self.Chicken_Frame)
        self.Chicken_Whole_Quantity.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Chicken_Whole_Quantity.setObjectName("Chicken_Whole_Quantity")
        self.horizontalLayout_61.addWidget(self.Chicken_Whole_Quantity)
        self.gridLayout_7.addLayout(self.horizontalLayout_61, 2, 0, 1, 1)
        self.horizontalLayout_52 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_52.setObjectName("horizontalLayout_52")
        self.Chicken_Legs = QtWidgets.QLabel(self.Chicken_Frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Chicken_Legs.setFont(font)
        self.Chicken_Legs.setObjectName("Chicken_Legs")
        self.horizontalLayout_52.addWidget(self.Chicken_Legs)
        self.Chicken_Legs_Price = QtWidgets.QLineEdit(self.Chicken_Frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Chicken_Legs_Price.setFont(font)
        self.Chicken_Legs_Price.setAutoFillBackground(False)
        self.Chicken_Legs_Price.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Chicken_Legs_Price.setText("")
        self.Chicken_Legs_Price.setReadOnly(True)
        self.Chicken_Legs_Price.setObjectName("Chicken_Legs_Price")
        self.horizontalLayout_52.addWidget(self.Chicken_Legs_Price)
        self.Chicken_Legs_Quantity = QtWidgets.QSpinBox(self.Chicken_Frame)
        self.Chicken_Legs_Quantity.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Chicken_Legs_Quantity.setObjectName("Chicken_Legs_Quantity")
        self.horizontalLayout_52.addWidget(self.Chicken_Legs_Quantity)
        self.gridLayout_7.addLayout(self.horizontalLayout_52, 4, 0, 1, 1)
        self.horizontalLayout_59 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_59.setObjectName("horizontalLayout_59")
        self.Chicken_Wings = QtWidgets.QLabel(self.Chicken_Frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Chicken_Wings.setFont(font)
        self.Chicken_Wings.setObjectName("Chicken_Wings")
        self.horizontalLayout_59.addWidget(self.Chicken_Wings)
        self.Chicken_Wings_Price = QtWidgets.QLineEdit(self.Chicken_Frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Chicken_Wings_Price.setFont(font)
        self.Chicken_Wings_Price.setAutoFillBackground(False)
        self.Chicken_Wings_Price.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Chicken_Wings_Price.setText("")
        self.Chicken_Wings_Price.setReadOnly(True)
        self.Chicken_Wings_Price.setObjectName("Chicken_Wings_Price")
        self.horizontalLayout_59.addWidget(self.Chicken_Wings_Price)
        self.Chicken_Wings_Quantity = QtWidgets.QSpinBox(self.Chicken_Frame)
        self.Chicken_Wings_Quantity.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Chicken_Wings_Quantity.setObjectName("Chicken_Wings_Quantity")
        self.horizontalLayout_59.addWidget(self.Chicken_Wings_Quantity)
        self.gridLayout_7.addLayout(self.horizontalLayout_59, 5, 0, 1, 1)
        self.line_5 = QtWidgets.QFrame(self.Chicken_Frame)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout_7.addWidget(self.line_5, 1, 0, 1, 1)
        self.Pork_Frame = QtWidgets.QFrame(self.frame_4)
        self.Pork_Frame.setGeometry(QtCore.QRect(10, 50, 221, 259))
        self.Pork_Frame.setAutoFillBackground(False)
        self.Pork_Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Pork_Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Pork_Frame.setObjectName("Pork_Frame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.Pork_Frame)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.Pork_Porkchop = QtWidgets.QLabel(self.Pork_Frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Pork_Porkchop.setFont(font)
        self.Pork_Porkchop.setObjectName("Pork_Porkchop")
        self.horizontalLayout_17.addWidget(self.Pork_Porkchop)
        self.Pork_Porkchop_Price = QtWidgets.QLineEdit(self.Pork_Frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Pork_Porkchop_Price.setFont(font)
        self.Pork_Porkchop_Price.setAutoFillBackground(False)
        self.Pork_Porkchop_Price.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Pork_Porkchop_Price.setText("")
        self.Pork_Porkchop_Price.setReadOnly(True)
        self.Pork_Porkchop_Price.setObjectName("Pork_Porkchop_Price")
        self.horizontalLayout_17.addWidget(self.Pork_Porkchop_Price)
        self.Pork_Porkchop_Quantity = QtWidgets.QSpinBox(self.Pork_Frame)
        self.Pork_Porkchop_Quantity.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Pork_Porkchop_Quantity.setObjectName("Pork_Porkchop_Quantity")
        self.horizontalLayout_17.addWidget(self.Pork_Porkchop_Quantity)
        self.gridLayout_4.addLayout(self.horizontalLayout_17, 5, 0, 1, 1)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.Pork_Porkloin = QtWidgets.QLabel(self.Pork_Frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Pork_Porkloin.setFont(font)
        self.Pork_Porkloin.setObjectName("Pork_Porkloin")
        self.horizontalLayout_18.addWidget(self.Pork_Porkloin)
        self.Pork_Porkloin_Price = QtWidgets.QLineEdit(self.Pork_Frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Pork_Porkloin_Price.setFont(font)
        self.Pork_Porkloin_Price.setAutoFillBackground(False)
        self.Pork_Porkloin_Price.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Pork_Porkloin_Price.setText("")
        self.Pork_Porkloin_Price.setReadOnly(True)
        self.Pork_Porkloin_Price.setObjectName("Pork_Porkloin_Price")
        self.horizontalLayout_18.addWidget(self.Pork_Porkloin_Price)
        self.Pork_Porkloin_Quantity = QtWidgets.QSpinBox(self.Pork_Frame)
        self.Pork_Porkloin_Quantity.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Pork_Porkloin_Quantity.setObjectName("Pork_Porkloin_Quantity")
        self.horizontalLayout_18.addWidget(self.Pork_Porkloin_Quantity)
        self.gridLayout_4.addLayout(self.horizontalLayout_18, 8, 0, 1, 1)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.Pork_Pigue = QtWidgets.QLabel(self.Pork_Frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Pork_Pigue.setFont(font)
        self.Pork_Pigue.setToolTip("")
        self.Pork_Pigue.setObjectName("Pork_Pigue")
        self.horizontalLayout_19.addWidget(self.Pork_Pigue)
        self.Pork_Pigue_Price = QtWidgets.QLineEdit(self.Pork_Frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Pork_Pigue_Price.setFont(font)
        self.Pork_Pigue_Price.setAutoFillBackground(False)
        self.Pork_Pigue_Price.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Pork_Pigue_Price.setText("")
        self.Pork_Pigue_Price.setReadOnly(True)
        self.Pork_Pigue_Price.setObjectName("Pork_Pigue_Price")
        self.horizontalLayout_19.addWidget(self.Pork_Pigue_Price)
        self.Pork_Pigue_Quantity = QtWidgets.QSpinBox(self.Pork_Frame)
        self.Pork_Pigue_Quantity.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Pork_Pigue_Quantity.setObjectName("Pork_Pigue_Quantity")
        self.horizontalLayout_19.addWidget(self.Pork_Pigue_Quantity)
        self.gridLayout_4.addLayout(self.horizontalLayout_19, 2, 0, 1, 1)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.Pork_Legs = QtWidgets.QLabel(self.Pork_Frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Pork_Legs.setFont(font)
        self.Pork_Legs.setObjectName("Pork_Legs")
        self.horizontalLayout_20.addWidget(self.Pork_Legs)
        self.Pork_Legs_Price = QtWidgets.QLineEdit(self.Pork_Frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Pork_Legs_Price.setFont(font)
        self.Pork_Legs_Price.setAutoFillBackground(False)
        self.Pork_Legs_Price.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Pork_Legs_Price.setText("")
        self.Pork_Legs_Price.setReadOnly(True)
        self.Pork_Legs_Price.setObjectName("Pork_Legs_Price")
        self.horizontalLayout_20.addWidget(self.Pork_Legs_Price)
        self.Pork_Legs_Quantity = QtWidgets.QSpinBox(self.Pork_Frame)
        self.Pork_Legs_Quantity.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Pork_Legs_Quantity.setObjectName("Pork_Legs_Quantity")
        self.horizontalLayout_20.addWidget(self.Pork_Legs_Quantity)
        self.gridLayout_4.addLayout(self.horizontalLayout_20, 6, 0, 1, 1)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.Pork_Kasim = QtWidgets.QLabel(self.Pork_Frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Pork_Kasim.setFont(font)
        self.Pork_Kasim.setObjectName("Pork_Kasim")
        self.horizontalLayout_21.addWidget(self.Pork_Kasim)
        self.Pork_Kasim_Price = QtWidgets.QLineEdit(self.Pork_Frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Pork_Kasim_Price.setFont(font)
        self.Pork_Kasim_Price.setAutoFillBackground(False)
        self.Pork_Kasim_Price.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Pork_Kasim_Price.setText("")
        self.Pork_Kasim_Price.setReadOnly(True)
        self.Pork_Kasim_Price.setObjectName("Pork_Kasim_Price")
        self.horizontalLayout_21.addWidget(self.Pork_Kasim_Price)
        self.Pork_Kasim_Quantity = QtWidgets.QSpinBox(self.Pork_Frame)
        self.Pork_Kasim_Quantity.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Pork_Kasim_Quantity.setObjectName("Pork_Kasim_Quantity")
        self.horizontalLayout_21.addWidget(self.Pork_Kasim_Quantity)
        self.gridLayout_4.addLayout(self.horizontalLayout_21, 3, 0, 1, 1)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.Pork_Liver_1 = QtWidgets.QLabel(self.Pork_Frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Pork_Liver_1.setFont(font)
        self.Pork_Liver_1.setObjectName("Pork_Liver_1")
        self.horizontalLayout_22.addWidget(self.Pork_Liver_1)
        self.Pork_Liver_Price = QtWidgets.QLineEdit(self.Pork_Frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Pork_Liver_Price.setFont(font)
        self.Pork_Liver_Price.setAutoFillBackground(False)
        self.Pork_Liver_Price.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Pork_Liver_Price.setText("")
        self.Pork_Liver_Price.setReadOnly(True)
        self.Pork_Liver_Price.setObjectName("Pork_Liver_Price")
        self.horizontalLayout_22.addWidget(self.Pork_Liver_Price)
        self.Pork_Liver_Quantity = QtWidgets.QSpinBox(self.Pork_Frame)
        self.Pork_Liver_Quantity.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Pork_Liver_Quantity.setObjectName("Pork_Liver_Quantity")
        self.horizontalLayout_22.addWidget(self.Pork_Liver_Quantity)
        self.gridLayout_4.addLayout(self.horizontalLayout_22, 7, 0, 1, 1)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.Pork = QtWidgets.QLabel(self.Pork_Frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Pork.setFont(font)
        self.Pork.setStyleSheet("")
        self.Pork.setObjectName("Pork")
        self.horizontalLayout_23.addWidget(self.Pork)
        self.line_6 = QtWidgets.QFrame(self.Pork_Frame)
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.horizontalLayout_23.addWidget(self.line_6)
        self.Pork_Prices = QtWidgets.QLabel(self.Pork_Frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Pork_Prices.setFont(font)
        self.Pork_Prices.setStyleSheet("")
        self.Pork_Prices.setObjectName("Pork_Prices")
        self.horizontalLayout_23.addWidget(self.Pork_Prices)
        self.line_7 = QtWidgets.QFrame(self.Pork_Frame)
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.horizontalLayout_23.addWidget(self.line_7)
        self.Pork_Quantities = QtWidgets.QLabel(self.Pork_Frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Pork_Quantities.setFont(font)
        self.Pork_Quantities.setAutoFillBackground(False)
        self.Pork_Quantities.setStyleSheet("")
        self.Pork_Quantities.setObjectName("Pork_Quantities")
        self.horizontalLayout_23.addWidget(self.Pork_Quantities)
        self.gridLayout_4.addLayout(self.horizontalLayout_23, 0, 0, 1, 1)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.Pork_Liempo = QtWidgets.QLabel(self.Pork_Frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Pork_Liempo.setFont(font)
        self.Pork_Liempo.setObjectName("Pork_Liempo")
        self.horizontalLayout_24.addWidget(self.Pork_Liempo)
        self.Pork_Liempo_Price = QtWidgets.QLineEdit(self.Pork_Frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Pork_Liempo_Price.setFont(font)
        self.Pork_Liempo_Price.setAutoFillBackground(False)
        self.Pork_Liempo_Price.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Pork_Liempo_Price.setText("")
        self.Pork_Liempo_Price.setReadOnly(True)
        self.Pork_Liempo_Price.setObjectName("Pork_Liempo_Price")
        self.horizontalLayout_24.addWidget(self.Pork_Liempo_Price)
        self.Pork_Liempo_Quantity = QtWidgets.QSpinBox(self.Pork_Frame)
        self.Pork_Liempo_Quantity.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Pork_Liempo_Quantity.setObjectName("Pork_Liempo_Quantity")
        self.horizontalLayout_24.addWidget(self.Pork_Liempo_Quantity)
        self.gridLayout_4.addLayout(self.horizontalLayout_24, 4, 0, 1, 1)
        self.horizontalLayout_62 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_62.setObjectName("horizontalLayout_62")
        self.Pork_Ribs_1 = QtWidgets.QLabel(self.Pork_Frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Pork_Ribs_1.setFont(font)
        self.Pork_Ribs_1.setObjectName("Pork_Ribs_1")
        self.horizontalLayout_62.addWidget(self.Pork_Ribs_1)
        self.Pork_Ribs_Price = QtWidgets.QLineEdit(self.Pork_Frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Pork_Ribs_Price.setFont(font)
        self.Pork_Ribs_Price.setAutoFillBackground(False)
        self.Pork_Ribs_Price.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Pork_Ribs_Price.setText("")
        self.Pork_Ribs_Price.setReadOnly(True)
        self.Pork_Ribs_Price.setObjectName("Pork_Ribs_Price")
        self.horizontalLayout_62.addWidget(self.Pork_Ribs_Price)
        self.Pork_Pork_Ribs_Quantity = QtWidgets.QSpinBox(self.Pork_Frame)
        self.Pork_Pork_Ribs_Quantity.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Pork_Pork_Ribs_Quantity.setObjectName("Pork_Pork_Ribs_Quantity")
        self.horizontalLayout_62.addWidget(self.Pork_Pork_Ribs_Quantity)
        self.gridLayout_4.addLayout(self.horizontalLayout_62, 9, 0, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.Pork_Frame)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_4.addWidget(self.line_3, 1, 0, 1, 1)
        self.Beef_Frame = QtWidgets.QFrame(self.frame_4)
        self.Beef_Frame.setGeometry(QtCore.QRect(250, 50, 221, 259))
        self.Beef_Frame.setStyleSheet("selection-color: rgb(113, 113, 113);")
        self.Beef_Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Beef_Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Beef_Frame.setObjectName("Beef_Frame")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.Beef_Frame)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.horizontalLayout_35 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")
        self.Beef_Tenderloin = QtWidgets.QLabel(self.Beef_Frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Beef_Tenderloin.setFont(font)
        self.Beef_Tenderloin.setObjectName("Beef_Tenderloin")
        self.horizontalLayout_35.addWidget(self.Beef_Tenderloin)
        self.Beef_Tenderloin_Price = QtWidgets.QLineEdit(self.Beef_Frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Beef_Tenderloin_Price.setFont(font)
        self.Beef_Tenderloin_Price.setAutoFillBackground(False)
        self.Beef_Tenderloin_Price.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Beef_Tenderloin_Price.setText("")
        self.Beef_Tenderloin_Price.setReadOnly(True)
        self.Beef_Tenderloin_Price.setObjectName("Beef_Tenderloin_Price")
        self.horizontalLayout_35.addWidget(self.Beef_Tenderloin_Price)
        self.Beef_Tenderloin_Quantity = QtWidgets.QSpinBox(self.Beef_Frame)
        self.Beef_Tenderloin_Quantity.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Beef_Tenderloin_Quantity.setObjectName("Beef_Tenderloin_Quantity")
        self.horizontalLayout_35.addWidget(self.Beef_Tenderloin_Quantity)
        self.gridLayout_5.addLayout(self.horizontalLayout_35, 7, 0, 1, 1)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.Beef_Topround = QtWidgets.QLabel(self.Beef_Frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Beef_Topround.setFont(font)
        self.Beef_Topround.setObjectName("Beef_Topround")
        self.horizontalLayout_27.addWidget(self.Beef_Topround)
        self.Beef_Topround_Price = QtWidgets.QLineEdit(self.Beef_Frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Beef_Topround_Price.setFont(font)
        self.Beef_Topround_Price.setAutoFillBackground(False)
        self.Beef_Topround_Price.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Beef_Topround_Price.setText("")
        self.Beef_Topround_Price.setReadOnly(True)
        self.Beef_Topround_Price.setObjectName("Beef_Topround_Price")
        self.horizontalLayout_27.addWidget(self.Beef_Topround_Price)
        self.Beef_Topround_Quantity = QtWidgets.QSpinBox(self.Beef_Frame)
        self.Beef_Topround_Quantity.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Beef_Topround_Quantity.setObjectName("Beef_Topround_Quantity")
        self.horizontalLayout_27.addWidget(self.Beef_Topround_Quantity)
        self.gridLayout_5.addLayout(self.horizontalLayout_27, 3, 0, 1, 1)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.Beef_Ribs = QtWidgets.QLabel(self.Beef_Frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Beef_Ribs.setFont(font)
        self.Beef_Ribs.setObjectName("Beef_Ribs")
        self.horizontalLayout_25.addWidget(self.Beef_Ribs)
        self.Beef_Beef_Ribs_Price = QtWidgets.QLineEdit(self.Beef_Frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Beef_Beef_Ribs_Price.setFont(font)
        self.Beef_Beef_Ribs_Price.setAutoFillBackground(False)
        self.Beef_Beef_Ribs_Price.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Beef_Beef_Ribs_Price.setText("")
        self.Beef_Beef_Ribs_Price.setReadOnly(True)
        self.Beef_Beef_Ribs_Price.setObjectName("Beef_Beef_Ribs_Price")
        self.horizontalLayout_25.addWidget(self.Beef_Beef_Ribs_Price)
        self.Beef_Beef_Ribs_Quantity = QtWidgets.QSpinBox(self.Beef_Frame)
        self.Beef_Beef_Ribs_Quantity.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Beef_Beef_Ribs_Quantity.setObjectName("Beef_Beef_Ribs_Quantity")
        self.horizontalLayout_25.addWidget(self.Beef_Beef_Ribs_Quantity)
        self.gridLayout_5.addLayout(self.horizontalLayout_25, 5, 0, 1, 1)
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.Beef_Bulalo = QtWidgets.QLabel(self.Beef_Frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Beef_Bulalo.setFont(font)
        self.Beef_Bulalo.setObjectName("Beef_Bulalo")
        self.horizontalLayout_29.addWidget(self.Beef_Bulalo)
        self.Beef_Bulalo_Price = QtWidgets.QLineEdit(self.Beef_Frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Beef_Bulalo_Price.setFont(font)
        self.Beef_Bulalo_Price.setAutoFillBackground(False)
        self.Beef_Bulalo_Price.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Beef_Bulalo_Price.setText("")
        self.Beef_Bulalo_Price.setReadOnly(True)
        self.Beef_Bulalo_Price.setObjectName("Beef_Bulalo_Price")
        self.horizontalLayout_29.addWidget(self.Beef_Bulalo_Price)
        self.Beef_Bulalo_Quantity = QtWidgets.QSpinBox(self.Beef_Frame)
        self.Beef_Bulalo_Quantity.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Beef_Bulalo_Quantity.setObjectName("Beef_Bulalo_Quantity")
        self.horizontalLayout_29.addWidget(self.Beef_Bulalo_Quantity)
        self.gridLayout_5.addLayout(self.horizontalLayout_29, 6, 0, 1, 1)
        self.horizontalLayout_36 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_36.setObjectName("horizontalLayout_36")
        self.Beef_T_bone = QtWidgets.QLabel(self.Beef_Frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Beef_T_bone.setFont(font)
        self.Beef_T_bone.setObjectName("Beef_T_bone")
        self.horizontalLayout_36.addWidget(self.Beef_T_bone)
        self.Beef_T_Bone_Price = QtWidgets.QLineEdit(self.Beef_Frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Beef_T_Bone_Price.setFont(font)
        self.Beef_T_Bone_Price.setAutoFillBackground(False)
        self.Beef_T_Bone_Price.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Beef_T_Bone_Price.setText("")
        self.Beef_T_Bone_Price.setReadOnly(True)
        self.Beef_T_Bone_Price.setObjectName("Beef_T_Bone_Price")
        self.horizontalLayout_36.addWidget(self.Beef_T_Bone_Price)
        self.Beef_T_Bone_Quantity = QtWidgets.QSpinBox(self.Beef_Frame)
        self.Beef_T_Bone_Quantity.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Beef_T_Bone_Quantity.setObjectName("Beef_T_Bone_Quantity")
        self.horizontalLayout_36.addWidget(self.Beef_T_Bone_Quantity)
        self.gridLayout_5.addLayout(self.horizontalLayout_36, 4, 0, 1, 1)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.Beef_Sirloin = QtWidgets.QLabel(self.Beef_Frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Beef_Sirloin.setFont(font)
        self.Beef_Sirloin.setObjectName("Beef_Sirloin")
        self.horizontalLayout_28.addWidget(self.Beef_Sirloin)
        self.Beef_Sirloin_Price = QtWidgets.QLineEdit(self.Beef_Frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Beef_Sirloin_Price.setFont(font)
        self.Beef_Sirloin_Price.setAutoFillBackground(False)
        self.Beef_Sirloin_Price.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Beef_Sirloin_Price.setText("")
        self.Beef_Sirloin_Price.setReadOnly(True)
        self.Beef_Sirloin_Price.setObjectName("Beef_Sirloin_Price")
        self.horizontalLayout_28.addWidget(self.Beef_Sirloin_Price)
        self.Beef_Sirloin_Quantity = QtWidgets.QSpinBox(self.Beef_Frame)
        self.Beef_Sirloin_Quantity.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Beef_Sirloin_Quantity.setObjectName("Beef_Sirloin_Quantity")
        self.horizontalLayout_28.addWidget(self.Beef_Sirloin_Quantity)
        self.gridLayout_5.addLayout(self.horizontalLayout_28, 2, 0, 1, 1)
        self.horizontalLayout_63 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_63.setObjectName("horizontalLayout_63")
        self.Beef_Kalitiran = QtWidgets.QLabel(self.Beef_Frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Beef_Kalitiran.setFont(font)
        self.Beef_Kalitiran.setObjectName("Beef_Kalitiran")
        self.horizontalLayout_63.addWidget(self.Beef_Kalitiran)
        self.Beef_Kalitiran_Price = QtWidgets.QLineEdit(self.Beef_Frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Beef_Kalitiran_Price.setFont(font)
        self.Beef_Kalitiran_Price.setAutoFillBackground(False)
        self.Beef_Kalitiran_Price.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Beef_Kalitiran_Price.setText("")
        self.Beef_Kalitiran_Price.setReadOnly(True)
        self.Beef_Kalitiran_Price.setObjectName("Beef_Kalitiran_Price")
        self.horizontalLayout_63.addWidget(self.Beef_Kalitiran_Price)
        self.Beef_Kalitiran_Quantity = QtWidgets.QSpinBox(self.Beef_Frame)
        self.Beef_Kalitiran_Quantity.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Beef_Kalitiran_Quantity.setObjectName("Beef_Kalitiran_Quantity")
        self.horizontalLayout_63.addWidget(self.Beef_Kalitiran_Quantity)
        self.gridLayout_5.addLayout(self.horizontalLayout_63, 9, 0, 1, 1)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.Beef_Oyster_Blade = QtWidgets.QLabel(self.Beef_Frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Beef_Oyster_Blade.setFont(font)
        self.Beef_Oyster_Blade.setObjectName("Beef_Oyster_Blade")
        self.horizontalLayout_26.addWidget(self.Beef_Oyster_Blade)
        self.Beef_Oyster_Blade_Price = QtWidgets.QLineEdit(self.Beef_Frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Beef_Oyster_Blade_Price.setFont(font)
        self.Beef_Oyster_Blade_Price.setAutoFillBackground(False)
        self.Beef_Oyster_Blade_Price.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Beef_Oyster_Blade_Price.setText("")
        self.Beef_Oyster_Blade_Price.setReadOnly(True)
        self.Beef_Oyster_Blade_Price.setObjectName("Beef_Oyster_Blade_Price")
        self.horizontalLayout_26.addWidget(self.Beef_Oyster_Blade_Price)
        self.Beef_Oyster_Blade_Quantity = QtWidgets.QSpinBox(self.Beef_Frame)
        self.Beef_Oyster_Blade_Quantity.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Beef_Oyster_Blade_Quantity.setObjectName("Beef_Oyster_Blade_Quantity")
        self.horizontalLayout_26.addWidget(self.Beef_Oyster_Blade_Quantity)
        self.gridLayout_5.addLayout(self.horizontalLayout_26, 8, 0, 1, 1)
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.Beef = QtWidgets.QLabel(self.Beef_Frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Beef.setFont(font)
        self.Beef.setStyleSheet("")
        self.Beef.setObjectName("Beef")
        self.horizontalLayout_34.addWidget(self.Beef)
        self.line_8 = QtWidgets.QFrame(self.Beef_Frame)
        self.line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.horizontalLayout_34.addWidget(self.line_8)
        self.Beef_Prices = QtWidgets.QLabel(self.Beef_Frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Beef_Prices.setFont(font)
        self.Beef_Prices.setStyleSheet("")
        self.Beef_Prices.setObjectName("Beef_Prices")
        self.horizontalLayout_34.addWidget(self.Beef_Prices)
        self.line_9 = QtWidgets.QFrame(self.Beef_Frame)
        self.line_9.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.horizontalLayout_34.addWidget(self.line_9)
        self.Beef_Quantities = QtWidgets.QLabel(self.Beef_Frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Beef_Quantities.setFont(font)
        self.Beef_Quantities.setStyleSheet("")
        self.Beef_Quantities.setObjectName("Beef_Quantities")
        self.horizontalLayout_34.addWidget(self.Beef_Quantities)
        self.gridLayout_5.addLayout(self.horizontalLayout_34, 0, 0, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.Beef_Frame)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout_5.addWidget(self.line_4, 1, 0, 1, 1)
        self.Meat_Shop_Management_System = QtWidgets.QLabel(self.frame_4)
        self.Meat_Shop_Management_System.setEnabled(True)
        self.Meat_Shop_Management_System.setGeometry(QtCore.QRect(0, 0, 721, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Meat_Shop_Management_System.setFont(font)
        self.Meat_Shop_Management_System.setStyleSheet("background-color: rgb(255, 89, 89);")
        self.Meat_Shop_Management_System.setObjectName("Meat_Shop_Management_System")
        self.Interface_Frame = QtWidgets.QFrame(self.frame_4)
        self.Interface_Frame.setGeometry(QtCore.QRect(0, 320, 721, 101))
        self.Interface_Frame.setStyleSheet("background-color: rgb(255, 89, 89);")
        self.Interface_Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Interface_Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Interface_Frame.setObjectName("Interface_Frame")
        self.layoutWidget_6 = QtWidgets.QWidget(self.Interface_Frame)
        self.layoutWidget_6.setGeometry(QtCore.QRect(250, 10, 171, 25))
        self.layoutWidget_6.setObjectName("layoutWidget_6")
        self.horizontalLayout_38 = QtWidgets.QHBoxLayout(self.layoutWidget_6)
        self.horizontalLayout_38.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_38.setObjectName("horizontalLayout_38")
        self.Change_Label = QtWidgets.QLabel(self.layoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.Change_Label.setFont(font)
        self.Change_Label.setObjectName("Change_Label")
        self.horizontalLayout_38.addWidget(self.Change_Label)
        self.Change_Output = QtWidgets.QLineEdit(self.layoutWidget_6)
        self.Change_Output.setStyleSheet("background-color: rgb(244, 244, 244);")
        self.Change_Output.setText("")
        self.Change_Output.setReadOnly(True)
        self.Change_Output.setObjectName("Change_Output")
        self.Change_Output.setText("0.0")
        self.horizontalLayout_38.addWidget(self.Change_Output)
        self.layoutWidget_5 = QtWidgets.QWidget(self.Interface_Frame)
        self.layoutWidget_5.setGeometry(QtCore.QRect(50, 10, 181, 52))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget_5)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.Total_Amount_Label = QtWidgets.QLabel(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.Total_Amount_Label.setFont(font)
        self.Total_Amount_Label.setObjectName("Total_Amount_Label")
        self.horizontalLayout_30.addWidget(self.Total_Amount_Label)
        self.Total_Amount_Display = QtWidgets.QLineEdit(self.layoutWidget_5)
        self.Total_Amount_Display.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Total_Amount_Display.setReadOnly(True)
        self.Total_Amount_Display.setObjectName("Total_Amount_Display")
        self.Total_Amount_Display.setText(str(0.0))
        self.horizontalLayout_30.addWidget(self.Total_Amount_Display)
        self.verticalLayout_2.addLayout(self.horizontalLayout_30)
        self.horizontalLayout_37 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_37.setObjectName("horizontalLayout_37")
        self.Received_Label = QtWidgets.QLabel(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.Received_Label.setFont(font)
        self.Received_Label.setObjectName("Received_Label")
        self.horizontalLayout_37.addWidget(self.Received_Label)
        self.Received_Input = QtWidgets.QLineEdit(self.layoutWidget_5)
        self.Received_Input.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Received_Input.setInputMask("")
        self.Received_Input.setText("")
        self.Received_Input.setPlaceholderText("")
        self.Received_Input.setObjectName("Received_Input")
        self.horizontalLayout_37.addWidget(self.Received_Input)
        self.verticalLayout_2.addLayout(self.horizontalLayout_37)
        self.Calculate_Button = QtWidgets.QPushButton(self.Interface_Frame)
        self.Calculate_Button.setGeometry(QtCore.QRect(320, 40, 101, 23))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.Calculate_Button.setFont(font)
        self.Calculate_Button.setStyleSheet("background-color: rgb(120, 195, 23);")
        self.Calculate_Button.setObjectName("Calculate_Button")
        
        self.Calculate_Button.clicked.connect(self.Calculate)
        self.layoutWidget = QtWidgets.QWidget(self.Interface_Frame)
        self.layoutWidget.setGeometry(QtCore.QRect(460, 10, 241, 58))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_39 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_39.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_39.setObjectName("horizontalLayout_39")
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.Get_Total_Amount_Button = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.Get_Total_Amount_Button.setFont(font)
        self.Get_Total_Amount_Button.setToolTip("")
        self.Get_Total_Amount_Button.setToolTipDuration(-1)
        self.Get_Total_Amount_Button.setStyleSheet("background-color: rgb(120, 195, 23);")
        self.Get_Total_Amount_Button.setObjectName("Get_Total_Amount_Button")
        self.Get_Total_Amount_Button.clicked.connect(self.Total_Amount)
        self.gridLayout_8.addWidget(self.Get_Total_Amount_Button, 0, 1, 1, 1)
        self.Update_Prices_Button = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.Update_Prices_Button.setFont(font)
        self.Update_Prices_Button.setStyleSheet("background-color: rgb(120, 195, 23);")
        self.Update_Prices_Button.setObjectName("Update_Prices_Button")
        self.Update_Prices_Button.clicked.connect(self.openWindow)
        

        self.gridLayout_8.addWidget(self.Update_Prices_Button, 1, 1, 1, 1)
        self.Refresh_Button = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.Refresh_Button.setFont(font)
        self.Refresh_Button.setStyleSheet("background-color: rgb(120, 195, 23);")
        self.Refresh_Button.setObjectName("Refresh_Button")
        self.Refresh_Button.clicked.connect(self.update_all)
        self.gridLayout_8.addWidget(self.Refresh_Button, 1, 0, 1, 1)
        self.Reset_Button_4 = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.Reset_Button_4.setFont(font)
        self.Reset_Button_4.setStyleSheet("background-color: rgb(120, 195, 23);")
        self.Reset_Button_4.setObjectName("Reset_Button_4")
        self.Reset_Button_4.clicked.connect(self.reset_quantity)
        self.gridLayout_8.addWidget(self.Reset_Button_4, 0, 0, 1, 1)
        self.horizontalLayout_39.addLayout(self.gridLayout_8)
        self.line = QtWidgets.QFrame(self.frame_4)
        self.line.setGeometry(QtCore.QRect(230, 50, 20, 271))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.frame_4)
        self.line_2.setGeometry(QtCore.QRect(470, 50, 20, 271))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.Pork_Frame.raise_()
        self.Chicken_Frame.raise_()
        self.Beef_Frame.raise_()
        self.line.raise_()
        self.line_2.raise_()
        self.Meat_Shop_Management_System.raise_()
        self.Interface_Frame.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")

        # Product Prices
        self.Pork_Price_List = [self.Pork_Pigue_Price, self.Pork_Kasim_Price,
                                self.Pork_Liempo_Price, self.Pork_Porkchop_Price,
                                self.Pork_Legs_Price, self.Pork_Liver_Price,
                                self.Pork_Porkloin_Price, self.Pork_Ribs_Price]

        self.Beef_Price_List = [self.Beef_Sirloin_Price, self.Beef_Topround_Price,
                                self.Beef_T_Bone_Price, self.Beef_Beef_Ribs_Price,
                                self.Beef_Bulalo_Price, self.Beef_Tenderloin_Price,
                                self.Beef_Oyster_Blade_Price, self.Beef_Kalitiran_Price]

        self.Chicken_Price_List = [self.Chicken_Whole_Price, self.Chicken_Breast_Price,
                                   self.Chicken_Legs_Price, self.Chicken_Wings_Price,
                                   self.Chicken_Drumstick_Price, self.Chicken_Gizzard_Price,
                                   self.Chicken_Liver_Price, self.Chicken_Feet_Price]

        self.update_all()

        # Product Quantity
        self.Chicken_Price_List = [self.Chicken_Whole_Price, self.Chicken_Breast_Price,
                                   self.Chicken_Legs_Price, self.Chicken_Wings_Price,
                                   self.Chicken_Drumstick_Price, self.Chicken_Gizzard_Price,
                                   self.Chicken_Liver_Price, self.Chicken_Feet_Price]
        
        self.Pork_Quantity_List = [self.Pork_Pigue_Quantity, self.Pork_Kasim_Quantity,
                                   self.Pork_Liempo_Quantity, self.Pork_Porkchop_Quantity,
                                   self.Pork_Legs_Quantity, self.Pork_Liver_Quantity,
                                   self.Pork_Porkloin_Quantity, self.Pork_Pork_Ribs_Quantity]
        
        self.Beef_Quantity_List = [self.Beef_Sirloin_Quantity, self.Beef_Topround_Quantity,
                                   self.Beef_T_Bone_Quantity, self.Beef_Beef_Ribs_Quantity,
                                   self.Beef_Bulalo_Quantity, self.Beef_Tenderloin_Quantity,
                                   self.Beef_Oyster_Blade_Quantity, self.Beef_Kalitiran_Quantity]

        self.Chicken_Quantity_List = [self.Chicken_Whole_Quantity, self.Chicken_Breast_Quantity,
                                      self.Chicken_Legs_Quantity, self.Chicken_Wings_Quantity,
                                      self.Chicken_Drumstick_Quantity, self.Chicken_Gizzard_Quantity,
                                      self.Chicken_Liver_Quantity, self.Chicken_Feet_Quantity]

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Chicken_Feet.setText(_translate("MainWindow", "Feet                 "))
        self.Chicken_Drumstick.setText(_translate("MainWindow", "Drumstick      "))
        self.Chicken_Liver.setText(_translate("MainWindow", "Liver                "))
        self.Chicken_Gizzard.setText(_translate("MainWindow", "Gizzard           "))
        self.Chicken_Breast.setText(_translate("MainWindow", "Breast             "))
        self.Chicken.setText(_translate("MainWindow", "Chicken          "))
        self.Chicken_Prices.setText(_translate("MainWindow", "Price"))
        self.Chicken_Quantities.setText(_translate("MainWindow", "Quantity"))
        self.Chicken_Whole.setText(_translate("MainWindow", "Whole              "))
        self.Chicken_Legs.setText(_translate("MainWindow", "Legs                 "))
        self.Chicken_Wings.setText(_translate("MainWindow", "Wings              "))
        self.Pork_Porkchop.setText(_translate("MainWindow", "Porkchop    "))
        self.Pork_Porkloin.setText(_translate("MainWindow", "Porkloin      "))
        self.Pork_Pigue.setText(_translate("MainWindow", "Pigue           "))
        self.Pork_Legs.setText(_translate("MainWindow", "Legs             "))
        self.Pork_Kasim.setText(_translate("MainWindow", "Kasim          "))
        self.Pork_Liver_1.setText(_translate("MainWindow", "Liver            "))
        self.Pork.setText(_translate("MainWindow", "Pork          "))
        self.Pork_Prices.setText(_translate("MainWindow", "Price           "))
        self.Pork_Quantities.setText(_translate("MainWindow", "Quantity"))
        self.Pork_Liempo.setText(_translate("MainWindow", "Liempo        "))
        self.Pork_Ribs_1.setText(_translate("MainWindow", "Pork ribs     "))
        self.Beef_Tenderloin.setText(_translate("MainWindow", "Tenderloin     "))
        self.Beef_Topround.setText(_translate("MainWindow", "Topround       "))
        self.Beef_Ribs.setText(_translate("MainWindow", "Beef Ribs        "))
        self.Beef_Bulalo.setText(_translate("MainWindow", "Bulalo              "))
        self.Beef_T_bone.setText(_translate("MainWindow", "T-bone            "))
        self.Beef_Sirloin.setText(_translate("MainWindow", "Sirloin             "))
        self.Beef_Kalitiran.setText(_translate("MainWindow", "Kalitiran         "))
        self.Beef_Oyster_Blade.setText(_translate("MainWindow", "Oyster Blade "))
        self.Beef.setText(_translate("MainWindow", "Beef                 "))
        self.Beef_Prices.setText(_translate("MainWindow", "Price"))
        self.Beef_Quantities.setText(_translate("MainWindow", "Quantity"))
        self.Meat_Shop_Management_System.setText(_translate("MainWindow", "█████████████████         Meat Shop Management System      ██████████████████"))
        self.Change_Label.setText(_translate("MainWindow", "Change    "))
        self.Total_Amount_Label.setText(_translate("MainWindow", "Total Amount   "))
        self.Received_Label.setText(_translate("MainWindow", "Received           "))
        self.Calculate_Button.setText(_translate("MainWindow", "Calculate"))
        self.Get_Total_Amount_Button.setStatusTip(_translate("MainWindow", "Total amount to pay"))
        self.Get_Total_Amount_Button.setText(_translate("MainWindow", "Get Total Amount"))
        self.Update_Prices_Button.setText(_translate("MainWindow", "Update Prices"))
        self.Refresh_Button.setText(_translate("MainWindow", "Refresh"))
        self.Reset_Button_4.setText(_translate("MainWindow", "Reset"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))

    def read_file(self, filename):
        with open(filename, "r") as file:
            prices = file.readlines()
        return prices

    def update_prices(self, List, filename):
        data_prices = self.read_file(filename)
        for index in range(0, len(List)):
            List[index].setText(data_prices[index])

    def update_all(self):
        self.update_prices(self.Pork_Price_List, "Pork_Prices.txt")
        self.update_prices(self.Beef_Price_List, "Beef_Prices.txt")
        self.update_prices(self.Chicken_Price_List, "Chicken_Prices.txt")

    def reset_quantity(self):        
        for quantity in self.Pork_Quantity_List:
            quantity.setValue(0)
        for quantity in self.Beef_Quantity_List:
            quantity.setValue(0)
        for quantity in self.Chicken_Quantity_List:
            quantity.setValue(0)
        self.Total_Amount_Display.setText(str(0.0))
        self.Change_Output.setText("0.0")
        self.Received_Input.setText("")

    def Total_Amount(self):
        total = 0.0
        for index in range(0, len(self.Pork_Quantity_List)):
            total += self.Pork_Quantity_List[index].value() * float(self.Pork_Price_List[index].text())
        for index in range(0, len(self.Beef_Quantity_List)):
            total += self.Beef_Quantity_List[index].value() * float(self.Beef_Price_List[index].text())
        for index in range(0, len(self.Chicken_Quantity_List)):
            total += self.Chicken_Quantity_List[index].value() * float(self.Chicken_Price_List[index].text())
        self.Total_Amount_Display.setText(str(total))

    def Calculate(self):
        try:
            if float(self.Received_Input.text()) >= float(self.Total_Amount_Display.text()):
                self.Change_Output.setText(str(float(self.Received_Input.text()) - float(self.Total_Amount_Display.text())))
            else:
                self.Change_Output.setText("Insufficient Funds!")
        except:
            pass


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

